### ISSUE TITLE
jmockit doesn't work with eclemma

### ISSUE THREAD

**Issue by PrzemekCh** [jmockit/jmockit1#187]
The solution proposed here doesn't work:
http://stackoverflow.com/questions/27316808/using-jmockit-with-eclemma

I'm using
		jmockit.version 1.18
		junit.version 4.12
		hamcrest-all.version 1.3

java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the schema (add/remove fields)
	at sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at uk.co.service.interceptor.JmsLoggerSoapInterceptorTest$2.<init>(JmsLoggerSoapInterceptorTest.java:100)
	at uk.co.service.interceptor.JmsLoggerSoapInterceptorTest.setUp(JmsLoggerSoapInterceptorTest.java:100)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by rliesenfeld** [comment]
This is not a problem in JMockit (since JMockit does not attempt to add/remove fields to classes, while EclEmma does). It's a problem in JaCoCo (Eclemma), which has already been solved in that project. You didn't say which version of EclEmma was used, so I assume it's not a recent one.

**Comment by PrzemekCh** [comment]
I'm using the latest version of Eclemma, but ok I'll report a bug with them.

Cheers
Prem
