### ISSUE TITLE
jmockit not support testng-6.9.4

### ISSUE THREAD

**Issue by cctvzd7** [jmockit/jmockit1#192]
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider mockit.integration.testng.internal.TestNGRunnerDecorator not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:231)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:181)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:365)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:445)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:945)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:895)
	at org.testng.TestNG.run(TestNG.java:1006)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:125)

**Comment by rliesenfeld** [comment]
I upgraded JMockit's own TestNG test suites to the latest version, TestNG 6.9.6, and they are all working fine. With 6.9.4 it also worked. Tested from Maven and from IntelliJ IDEA.

So, I would need more information to reproduce the problem.

**Comment by virgo47** [comment]
Not sure how related this is, but while using JMockit 1.18 I recently upgraded from TestNG 6.8.8 to 6.9.4 and @Mocked fields in my test were null. Also no "JMockit: Reinitializing under custom class loader java.net.URLClassLoader..." message appeared. The same with JMockit 1.19.

However, with TestNG 6.9.6 I don't have this problem anymore (tried it after reading this report). If it's related to original poster's problem, TestNG upgrade may help.
