### ISSUE TITLE
Version 1.18 does not work with Oracle JDK 7

### ISSUE THREAD

**Issue by alexandarp** [jmockit/jmockit1#199]
Everything was running fine on OpenJDK except that I was required to pass the ```-javaagent``` parameter in the maven surefire config. I then decided to switch the CI server to Oracle JDK 7 to see if I could avoid using ```-javaagent``` in the pom file. 

I now get the following error:

```
Full thread dump Java HotSpot(TM) 64-Bit Server VM (24.79-b02 mixed mode):
"Service Thread" daemon prio=10 tid=0x00007fc5c80b2800 nid=0x159 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
"C2 CompilerThread1" daemon prio=10 tid=0x00007fc5c80b0000 nid=0x158 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
"C2 CompilerThread0" daemon prio=10 tid=0x00007fc5c80ad800 nid=0x157 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
"Signal Dispatcher" daemon prio=10 tid=0x00007fc5c80ab800 nid=0x156 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE
"Finalizer" daemon prio=10 tid=0x00007fc5c808b800 nid=0x155 in Object.wait() [0x00007fc5ccd09000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(Native Method)
	- waiting on <0x00000000f07be978> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:135)
	- locked <0x00000000f07be978> (a java.lang.ref.ReferenceQueue$Lock)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:151)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)
```

I should add that I am using Maven surefire version ```2.18.1``` and Maven ```3.3.3```. I did however fix the above error by passing the ```javaagent``` parameter in the maven surefire configuration. My tests are currently running but are throwing ```null``` errors. Is there any special configuration or setting I need to add to use the Oracle JDK?

**Comment by alexandarp** [comment]
Here is the output when I run ```java -v```
```
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

**Comment by rliesenfeld** [comment]
I am unable to reproduce the problem; would need more information, such as an example Maven-based project, including a pom.xml and a test class.
