### ISSUE TITLE
Breaks when using randomizedtesting runner

### ISSUE THREAD

**Issue by ferronrsmith** [jmockit/jmockit1#223]
Doesn't seem to work with [randomizedtesting](https://github.com/randomizedtesting/randomizedtesting) [RandomizedRunner](https://github.com/randomizedtesting/randomizedtesting/blob/master/randomized-runner/src/main/java/com/carrotsearch/randomizedtesting/RandomizedRunner.java)

```java
/usr/lib/jvm/java-8-oracle/bin/java -ea -Xmx2048m -Xms1024m -XX:+CMSClassUnloadingEnabled -Dlog4j.properties=log4j-test.xml -Dfile.encoding=UTF-8 -DthreadLocal=false -DcongoCluster=test -DengineCluster=test -Didea.launcher.port=7532 -Didea.launcher.bin.path=/home/ferron/dev_apps/idea/bin -Didea.junit.sm_runner -classpath /home/ferron/dev_apps/idea/lib/idea_rt.jar:/home/ferron/dev_apps/idea/plugins/junit/lib/junit-rt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/ferron/work/workspacetest/future/bindle/model/target/test-classes:/home/ferron/work/workspacetest/future/bindle/model/target/classes:/home/ferron/.m2/repository/com/testinc/common-utils/29/common-utils-29.jar:/home/ferron/work/workspacetest/future/bindle/congo/target/classes:/home/ferron/.m2/repository/com/testinc/common-jackson/29/common-jackson-29.jar:/home/ferron/work/workspacetest/future/bindle/configuration/target/classes:/home/ferron/.m2/repository/com/edropple/jregex/jregex/1.2_01/jregex-1.2_01.jar:/home/ferron/.m2/repository/com/googlecode/jcsv/jcsv/1.4.0/jcsv-1.4.0.jar:/home/ferron/.m2/repository/org/elasticsearch/elasticsearch/1.4.4/elasticsearch-1.4.4.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-analyzers-common/4.10.3/lucene-analyzers-common-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-queries/4.10.3/lucene-queries-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-memory/4.10.3/lucene-memory-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-highlighter/4.10.3/lucene-highlighter-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-queryparser/4.10.3/lucene-queryparser-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-sandbox/4.10.3/lucene-sandbox-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-suggest/4.10.3/lucene-suggest-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-misc/4.10.3/lucene-misc-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-join/4.10.3/lucene-join-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-grouping/4.10.3/lucene-grouping-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-spatial/4.10.3/lucene-spatial-4.10.3.jar:/home/ferron/.m2/repository/com/spatial4j/spatial4j/0.4.1/spatial4j-0.4.1.jar:/home/ferron/.m2/repository/org/antlr/antlr-runtime/3.5/antlr-runtime-3.5.jar:/home/ferron/.m2/repository/org/ow2/asm/asm/4.1/asm-4.1.jar:/home/ferron/.m2/repository/org/ow2/asm/asm-commons/4.1/asm-commons-4.1.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-expressions/4.10.3/lucene-expressions-4.10.3.jar:/home/ferron/.m2/repository/org/reflections/reflections/0.9.9/reflections-0.9.9.jar:/home/ferron/.m2/repository/com/google/guava/guava/15.0/guava-15.0.jar:/home/ferron/.m2/repository/org/javassist/javassist/3.18.2-GA/javassist-3.18.2-GA.jar:/home/ferron/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar:/home/ferron/work/workspacetest/future/bindle/target/classes:/home/ferron/.m2/repository/com/testinc/common-net/29/common-net-29.jar:/home/ferron/work/workspacetest/future/bindle/configuration/target/test-classes:/home/ferron/work/workspacetest/future/bindle/congo/target/test-classes:/home/ferron/.m2/repository/org/mockito/mockito-core/1.10.19/mockito-core-1.10.19.jar:/home/ferron/.m2/repository/org/objenesis/objenesis/2.1/objenesis-2.1.jar:/home/ferron/.m2/repository/org/codehaus/mojo/selenium-maven-plugin/2.3/selenium-maven-plugin-2.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/gmaven-mojo/1.3/gmaven-mojo-1.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-api/1.3/gmaven-runtime-api-1.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-api/1.3/gmaven-feature-api-1.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-1.5/1.3/gmaven-runtime-1.5-1.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/feature/gmaven-feature-support/1.3/gmaven-feature-support-1.3.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/runtime/gmaven-runtime-support/1.3/gmaven-runtime-support-1.3.jar:/home/ferron/.m2/repository/org/sonatype/gshell/gshell-io/2.0/gshell-io-2.0.jar:/home/ferron/.m2/repository/com/thoughtworks/qdox/qdox/1.10/qdox-1.10.jar:/home/ferron/.m2/repository/jline/jline/0.9.94/jline-0.9.94.jar:/home/ferron/.m2/repository/org/apache/maven/maven-project/2.0.10/maven-project-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/maven-settings/2.0.10/maven-settings-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/maven-profile/2.0.10/maven-profile-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/maven-artifact-manager/2.0.10/maven-artifact-manager-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/maven-repository-metadata/2.0.10/maven-repository-metadata-2.0.10.jar:/home/ferron/.m2/repository/org/apache/maven/wagon/wagon-provider-api/1.0-beta-2/wagon-provider-api-1.0-beta-2.jar:/home/ferron/.m2/repository/org/apache/maven/maven-plugin-registry/2.0.10/maven-plugin-registry-2.0.10.jar:/home/ferron/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar:/home/ferron/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.5/plexus-utils-1.5.5.jar:/home/ferron/.m2/repository/org/apache/maven/maven-artifact/2.0.10/maven-artifact-2.0.10.jar:/home/ferron/.m2/repository/org/codehaus/plexus/plexus-container-default/1.0-alpha-9-stable-1/plexus-container-default-1.0-alpha-9-stable-1.jar:/home/ferron/.m2/repository/classworlds/classworlds/1.1-alpha-2/classworlds-1.1-alpha-2.jar:/home/ferron/.m2/repository/org/apache/maven/maven-plugin-api/2.0.10/maven-plugin-api-2.0.10.jar:/home/ferron/.m2/repository/org/codehaus/gmaven/gmaven-mojo-support/1.3/gmaven-mojo-support-1.3.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-server/2.21.0/selenium-server-2.21.0.jar:/home/ferron/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.47/bcprov-jdk15on-1.47.jar:/home/ferron/.m2/repository/mx4j/mx4j-tools/3.0.1/mx4j-tools-3.0.1.jar:/home/ferron/.m2/repository/org/mortbay/jetty/servlet-api-2.5/6.1.9/servlet-api-2.5-6.1.9.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/jetty-repacked/7.6.1/jetty-repacked-7.6.1.jar:/home/ferron/.m2/repository/net/jcip/jcip-annotations/1.0/jcip-annotations-1.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-java/2.21.0/selenium-java-2.21.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-android-driver/2.21.0/selenium-android-driver-2.21.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-safari-driver/2.21.0/selenium-safari-driver-2.21.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-support/2.21.0/selenium-support-2.21.0.jar:/home/ferron/.m2/repository/org/webbitserver/webbit/0.4.6/webbit-0.4.6.jar:/home/ferron/.m2/repository/org/jboss/netty/netty/3.2.7.Final/netty-3.2.7.Final.jar:/home/ferron/.m2/repository/org/yaml/snakeyaml/1.8/snakeyaml-1.8.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-remote-driver/2.21.0/selenium-remote-driver-2.21.0.jar:/home/ferron/.m2/repository/net/java/dev/jna/jna/3.4.0/jna-3.4.0.jar:/home/ferron/.m2/repository/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-api/2.21.0/selenium-api-2.21.0.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-remote-control/2.0rc2/selenium-remote-control-2.0rc2.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-chrome-driver/2.0rc2/selenium-chrome-driver-2.0rc2.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-htmlunit-driver/2.0rc2/selenium-htmlunit-driver-2.0rc2.jar:/home/ferron/.m2/repository/net/sourceforge/htmlunit/htmlunit/2.8/htmlunit-2.8.jar:/home/ferron/.m2/repository/xalan/xalan/2.7.1/xalan-2.7.1.jar:/home/ferron/.m2/repository/xalan/serializer/2.7.1/serializer-2.7.1.jar:/home/ferron/.m2/repository/commons-collections/commons-collections/3.2.1/commons-collections-3.2.1.jar:/home/ferron/.m2/repository/org/apache/httpcomponents/httpmime/4.0.1/httpmime-4.0.1.jar:/home/ferron/.m2/repository/org/apache/james/apache-mime4j/0.6/apache-mime4j-0.6.jar:/home/ferron/.m2/repository/net/sourceforge/htmlunit/htmlunit-core-js/2.8/htmlunit-core-js-2.8.jar:/home/ferron/.m2/repository/net/sourceforge/nekohtml/nekohtml/1.9.14/nekohtml-1.9.14.jar:/home/ferron/.m2/repository/net/sourceforge/cssparser/cssparser/0.9.5/cssparser-0.9.5.jar:/home/ferron/.m2/repository/org/w3c/css/sac/1.3/sac-1.3.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-firefox-driver/2.0rc2/selenium-firefox-driver-2.0rc2.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-ie-driver/2.0rc2/selenium-ie-driver-2.0rc2.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/selenium-iphone-driver/2.0rc2/selenium-iphone-driver-2.0rc2.jar:/home/ferron/.m2/repository/bouncycastle/bcprov-jdk15/140/bcprov-jdk15-140.jar:/home/ferron/.m2/repository/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar:/home/ferron/.m2/repository/commons-logging/commons-logging/1.1.1/commons-logging-1.1.1.jar:/home/ferron/.m2/repository/org/seleniumhq/selenium/client-drivers/selenium-java-client-driver/1.0.2/selenium-java-client-driver-1.0.2.jar:/home/ferron/.m2/repository/javax/servlet/servlet-api/2.4/servlet-api-2.4.jar:/home/ferron/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/home/ferron/.m2/repository/commons-codec/commons-codec/1.5/commons-codec-1.5.jar:/home/ferron/.m2/repository/org/httpunit/httpunit/1.7.2/httpunit-1.7.2.jar:/home/ferron/.m2/repository/rhino/js/1.6R5/js-1.6R5.jar:/home/ferron/.m2/repository/nekohtml/nekohtml/0.9.5/nekohtml-0.9.5.jar:/home/ferron/.m2/repository/net/sf/jtidy/jtidy/r938/jtidy-r938.jar:/home/ferron/.m2/repository/xerces/xercesImpl/2.6.1/xercesImpl-2.6.1.jar:/home/ferron/.m2/repository/xerces/xmlParserAPIs/2.6.1/xmlParserAPIs-2.6.1.jar:/home/ferron/.m2/repository/com/github/stefanbirkner/system-rules/1.5.0/system-rules-1.5.0.jar:/home/ferron/.m2/repository/commons-io/commons-io/2.6-SNAPSHOT/commons-io-2.6-20150921.222343-2.jar:/home/ferron/.m2/repository/org/springframework/spring-core/4.1.4.RELEASE/spring-core-4.1.4.RELEASE.jar:/home/ferron/.m2/repository/org/springframework/spring-test/4.1.4.RELEASE/spring-test-4.1.4.RELEASE.jar:/home/ferron/.m2/repository/org/mockftpserver/MockFtpServer/2.4/MockFtpServer-2.4.jar:/home/ferron/.m2/repository/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar:/home/ferron/.m2/repository/xml-apis/xml-apis/1.0.b2/xml-apis-1.0.b2.jar:/home/ferron/.m2/repository/com/carrotsearch/randomizedtesting/randomizedtesting-runner/2.1.17/randomizedtesting-runner-2.1.17.jar:/home/ferron/.m2/repository/org/elasticsearch/elasticsearch/1.4.4/elasticsearch-1.4.4-tests.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-test-framework/4.10.3/lucene-test-framework-4.10.3.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-codecs/4.10.3/lucene-codecs-4.10.3.jar:/home/ferron/.m2/repository/com/carrotsearch/randomizedtesting/junit4-ant/2.1.6/junit4-ant-2.1.6.jar:/home/ferron/.m2/repository/org/apache/ant/ant/1.8.2/ant-1.8.2.jar:/home/ferron/.m2/repository/org/apache/lucene/lucene-core/4.10.3/lucene-core-4.10.3.jar:/home/ferron/.m2/repository/org/codehaus/groovy/groovy-all/2.3.2/groovy-all-2.3.2.jar:/home/ferron/.m2/repository/org/skyscreamer/jsonassert/1.2.2/jsonassert-1.2.2.jar:/home/ferron/.m2/repository/org/json/json/20090211/json-20090211.jar:/home/ferron/.m2/repository/com/github/tomakehurst/wiremock/2.0.6-beta/wiremock-2.0.6-beta.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-server/9.2.8.v20150217/jetty-server-9.2.8.v20150217.jar:/home/ferron/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-http/9.2.8.v20150217/jetty-http-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-util/9.2.8.v20150217/jetty-util-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-io/9.2.8.v20150217/jetty-io-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-servlet/9.2.8.v20150217/jetty-servlet-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-security/9.2.8.v20150217/jetty-security-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-webapp/9.2.8.v20150217/jetty-webapp-9.2.8.v20150217.jar:/home/ferron/.m2/repository/org/eclipse/jetty/jetty-xml/9.2.8.v20150217/jetty-xml-9.2.8.v20150217.jar:/home/ferron/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.6.1/jackson-core-2.6.1.jar:/home/ferron/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.6.1/jackson-annotations-2.6.1.jar:/home/ferron/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.6.1/jackson-databind-2.6.1.jar:/home/ferron/.m2/repository/org/apache/httpcomponents/httpclient/4.5/httpclient-4.5.jar:/home/ferron/.m2/repository/org/apache/httpcomponents/httpcore/4.4.1/httpcore-4.4.1.jar:/home/ferron/.m2/repository/xmlunit/xmlunit/1.6/xmlunit-1.6.jar:/home/ferron/.m2/repository/com/jayway/jsonpath/json-path/2.0.0/json-path-2.0.0.jar:/home/ferron/.m2/repository/net/minidev/json-smart/2.1.1/json-smart-2.1.1.jar:/home/ferron/.m2/repository/net/minidev/asm/1.0.2/asm-1.0.2.jar:/home/ferron/.m2/repository/asm/asm/3.3.1/asm-3.3.1.jar:/home/ferron/.m2/repository/net/sf/jopt-simple/jopt-simple/4.9/jopt-simple-4.9.jar:/home/ferron/.m2/repository/com/jayway/awaitility/awaitility/1.6.5/awaitility-1.6.5.jar:/home/ferron/.m2/repository/org/hamcrest/hamcrest-library/1.3/hamcrest-library-1.3.jar:/home/ferron/.m2/repository/cglib/cglib-nodep/3.1/cglib-nodep-3.1.jar:/home/ferron/.m2/repository/com/rabbitmq/amqp-client/3.4.3/amqp-client-3.4.3.jar:/home/ferron/.m2/repository/org/slf4j/slf4j-api/1.7.10/slf4j-api-1.7.10.jar:/home/ferron/.m2/repository/org/slf4j/slf4j-log4j12/1.7.10/slf4j-log4j12-1.7.10.jar:/home/ferron/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/home/ferron/.m2/repository/com/sun/mail/javax.mail/1.5.2/javax.mail-1.5.2.jar:/home/ferron/.m2/repository/javax/activation/activation/1.1/activation-1.1.jar:/home/ferron/.m2/repository/com/testinc/common-test/29/common-test-29.jar:/home/ferron/.m2/repository/org/apache/commons/commons-lang3/3.1/commons-lang3-3.1.jar:/home/ferron/.m2/repository/org/jmockit/jmockit/1.19/jmockit-1.19.jar:/home/ferron/.m2/repository/junit/junit/4.12/junit-4.12.jar:/home/ferron/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar com.intellij.rt.execution.application.AppMain com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 com.testinc.util.CongoOutputStreamTest,testWriteEntries
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd                       -Dsun.java2d.xrender=true
log4j:WARN No appenders could be found for logger (org.elasticsearch.test).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

java.lang.IllegalStateException: Invalid place to record expectations

	at __randomizedtesting.SeedInfo.seed([E188E030803CB62B:D5CE9AC9B3423E37]:0)
	at com.testinc.util.CongoOutputStreamTest$1.<init>(CongoOutputStreamTest.java:26)
	at com.testinc.util.CongoOutputStreamTest.testWriteEntries(CongoOutputStreamTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.invoke(RandomizedRunner.java:1665)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$8.evaluate(RandomizedRunner.java:864)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$9.evaluate(RandomizedRunner.java:900)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$10.evaluate(RandomizedRunner.java:914)
	at org.apache.lucene.util.TestRuleSetupTeardownChained$1.evaluate(TestRuleSetupTeardownChained.java:50)
	at org.apache.lucene.util.TestRuleFieldCacheSanity$1.evaluate(TestRuleFieldCacheSanity.java:51)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at com.carrotsearch.randomizedtesting.rules.SystemPropertiesInvariantRule$1.evaluate(SystemPropertiesInvariantRule.java:59)
	at org.apache.lucene.util.TestRuleThreadAndTestName$1.evaluate(TestRuleThreadAndTestName.java:49)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl.forkTimeoutingTask(ThreadLeakControl.java:809)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$3.evaluate(ThreadLeakControl.java:460)
	at com.carrotsearch.randomizedtesting.RandomizedRunner.runSingleTest(RandomizedRunner.java:873)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$5.evaluate(RandomizedRunner.java:775)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$6.evaluate(RandomizedRunner.java:809)
	at com.carrotsearch.randomizedtesting.RandomizedRunner$7.evaluate(RandomizedRunner.java:820)
	at org.apache.lucene.util.AbstractBeforeAfterRule$1.evaluate(AbstractBeforeAfterRule.java:46)
	at org.apache.lucene.util.TestRuleStoreClassName$1.evaluate(TestRuleStoreClassName.java:42)
	at com.carrotsearch.randomizedtesting.rules.SystemPropertiesInvariantRule$1.evaluate(SystemPropertiesInvariantRule.java:59)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:39)
	at com.carrotsearch.randomizedtesting.rules.NoShadowingOrOverridesOnMethodsRule$1.evaluate(NoShadowingOrOverridesOnMethodsRule.java:39)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at org.apache.lucene.util.TestRuleAssertionsRequired$1.evaluate(TestRuleAssertionsRequired.java:54)
	at org.apache.lucene.util.TestRuleMarkFailure$1.evaluate(TestRuleMarkFailure.java:48)
	at org.apache.lucene.util.TestRuleIgnoreAfterMaxFailures$1.evaluate(TestRuleIgnoreAfterMaxFailures.java:65)
	at org.apache.lucene.util.TestRuleIgnoreTestSuites$1.evaluate(TestRuleIgnoreTestSuites.java:55)
	at com.carrotsearch.randomizedtesting.rules.StatementAdapter.evaluate(StatementAdapter.java:36)
	at com.carrotsearch.randomizedtesting.ThreadLeakControl$StatementRunner.run(ThreadLeakControl.java:367)
	at java.lang.Thread.run(Thread.java:745)


Process finished with exit code 255
```

**Comment by rliesenfeld** [comment]
Ok, noted.
