### ISSUE TITLE
Using JMockit in Eclipse JUnit Plugin-Tests

### ISSUE THREAD

**Issue by ChristophLu** [jmockit/jmockit1#242]
When using JMockit in a JUnit-Plugin test (not the regular one), eclipse adds a OSGi context. To run it I had to add the javaagent in the VM arguments. The test interrupts during a VerifyError exception which I could suppress with a `-noverify` in the VM arguments. The exception I got then is the following:

    java.lang.NoClassDefFoundError: mockit/internal/state/TestRun
            at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java)
            at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
            at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
            at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
            at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
            at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
            at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
            at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
            at mockit.integration.junit4.JMockit.<init>(JMockit.java:30)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
            at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
            at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
            at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
            at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
            at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
            at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
            at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
            at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
            at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
            at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
            at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
            at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
            at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
            at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
            at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
            at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
    Caused by: java.lang.ClassNotFoundException: mockit.internal.state.TestRun cannot be found by org.junit_4.12.0.v201504281640
            at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:439)
            at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:352)
            at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:344)
            at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
            at org.junit.runners.model.FrameworkMethod.validatePublicVoidNoArg(FrameworkMethod.java)
            at org.junit.runners.ParentRunner.validatePublicVoidNoArgMethods(ParentRunner.java:155)
            at org.junit.runners.BlockJUnit4ClassRunner.validateTestMethods(BlockJUnit4ClassRunner.java:208)
            at org.junit.runners.BlockJUnit4ClassRunner.validateInstanceMethods(BlockJUnit4ClassRunner.java:188)
            at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:128)
            at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
            at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
            at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
            at mockit.integration.junit4.JMockit.<init>(JMockit.java:30)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
            at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
            at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
            at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
            at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
            at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
            at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
            at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
            at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
            at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
            at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
            at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
            at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:156)
            at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:82)
            at org.eclipse.tycho.surefire.osgibooter.OsgiSurefireBooter.run(OsgiSurefireBooter.java:91)
            at org.eclipse.tycho.surefire.osgibooter.HeadlessTestApplication.run(HeadlessTestApplication.java:21)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.eclipse.equinox.internal.app.EclipseAppContainer.callMethodWithException(EclipseAppContainer.java:587)
            at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:198)
            at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
            at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
            at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
            at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
            at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
            at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
            at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
            at java.lang.reflect.Method.invoke(Method.java:497)
            at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
            at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
            at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
            at org.eclipse.equinox.launcher.Main.main(Main.java:1488)

The JAR file of jmockit is used as plugin dependency in manifest and is also added to the build path of the project. Both are using the same file: `org.jmockit-1.20.0.jar`. 
If I run the tests with the normal JUnit tests of eclipse, everything works perfectly. Any ideas?

**Comment by rliesenfeld** [comment]
I don't use Eclipse or OSGi. If someone else wants to work on adding support for OSGi custom classloading, I would welcome it. Otherwise, I will have to close the issue as "won't fix".

**Comment by rliesenfeld** [comment]
In this case, the user didn't actually need to run tests on an OSGi environment.

If someone wishes to re-open the issue and submit a PR adding OSGi support, I would appreciate it.
