### ISSUE TITLE
Fatal error: processing of -javaagent failed

### ISSUE THREAD

**Issue by Staanie** [jmockit/jmockit1#28]
Hi,

I get the following stack trace trying to run tests with JMockit:

Ausnahmebedingung in Thread "main"# START NON-TRANSLATABLEjava.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:60)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
    at java.lang.reflect.Method.invoke(Method.java:611)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:335)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:350)
Caused by: java.lang.ClassFormatError: JVMCFRE009 Schnittstellenfeld muss 'public', 'static' oder 'final' sein.; Klasse=org/omg/CORBA/portable/IDLEntity, Offset=198
    at com.ibm.oti.vm.VM.findClassOrNull(Native Method)
    at com.ibm.oti.vm.BootstrapClassLoader.loadClass(BootstrapClassLoader.java:62)
    at com.ibm.oti.vm.VM.findClassOrNull(Native Method)
    at com.ibm.oti.vm.BootstrapClassLoader.loadClass(BootstrapClassLoader.java:62)
    at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:655)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:644)
    at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:657)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:644)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:358)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:627)
    at mockit.internal.startup.MockingBridgeFields.createSyntheticFieldsInJREClassToHoldMockingBridges(MockingBridgeFields.java:30)
    at mockit.internal.startup.Startup.initialize(Startup.java:57)
    at mockit.internal.startup.Startup.premain(Startup.java:49)
    ... 6 more

Used to work well with prior versions of JMockit, including 1.9, only changed JMockit version to 1.10.
Any ideas why it won't work anymore?

JMockit: 1.10
JRE: WebSphere Application Servers V8.5 JRE (Java 1.7)
JUnit: 4.10

**Comment by fw-aaron** [comment]
Bravo @rliesenfeld !
