### ISSUE TITLE
minTimes = 0 stopped working

### ISSUE THREAD

**Issue by Milbor** [jmockit/jmockit1#319]
This fails in 1.26 but was passing in 1.25:
```
public class SpikeTest {
    @Injectable
    private Service service;

    interface Service {
        void call();
    }

    @Test
    public void test() throws Exception {
        new Expectations() {{
            service.call();
            minTimes = 0;
        }};
    }
}
```
```
mockit.internal.MissingInvocation: Missing 1 invocation to:
cz.csob.spike.SpikeTest$Service#call()
   on mock instance: cz.csob.spike.$Proxy4@5ed241cb
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:109)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: Missing invocations
	at cz.csob.spike.SpikeTest$1.<init>(SpikeTest.java:19)
	at cz.csob.spike.SpikeTest.test(SpikeTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:606)
	... 10 more
```

I don't see this mentioned in release notes. Has anything changed? Thanks

**Comment by rliesenfeld** [comment]
Same as #315. The behavior change has been documented in the API documentation for the next release (1.27).
