### ISSUE TITLE
Mocking is not replayed when mocked object is accessed from EventQueue

### ISSUE THREAD

**Issue by hamid-nazari** [jmockit/jmockit1#327]
Seen on JMockit 1.23 to JMockit 1.27

Playing a previously recorded behavior on EDT will execute the actual code, instead of the mocked behavior. Consider the following test case:

> public static class TestClass
> 	{
> 		String value;
> 
> 		public String getValue()
> 		{
> 			return value;
> 		}
> 	}
> 
> 	@Mocked
> 	private TestClass testClass;
> 
> 	@Test
> 	public void test() throws InvocationTargetException, InterruptedException
> 	{
> 
> 		new Expectations()
> 		{
> 			{
> 				testClass.getValue();
> 				result = "value";
> 			}
> 		};
> 
> 		assertEquals(testClass.getValue(), "value");
> 
> 		new Thread(() -> assertEquals(testClass.getValue(), "value")).start();
> 
> 		EventQueue.invokeAndWait(() -> assertEquals(testClass.getValue(), "value"));
> 	}
> 

This test fails with JMockit 1.23 and above like this:
```
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1321)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1296)
	at EDTFailure.test(EDTFailure.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
Caused by: java.lang.AssertionError: expected [value] but found [no-value]
	at EDTFailure.lambda$1(EDTFailure.java:42)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

which confirms that the actual code has been executed from EDT.

**Comment by rliesenfeld** [comment]
Yes, calls from special threads like the EDT or the finalization thread are not mocked. This is done to prevent obscure failures which were observed to happen in the past.
