### ISSUE TITLE
Invalid mock-up for internal class

### ISSUE THREAD

**Issue by Lewox** [jmockit/jmockit1#332]
JMockit 1.27, TestNG 6.9.10, Java 8

I'm getting the following warning, I moved from version 1.21 to 1.27:
```
java.lang.IllegalArgumentException: Invalid mock-up for internal class TestDAO; remove it to avoid this warning
	at MainTest$1.<init>(MainTest.java:21)
	at MainTest.test(MainTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by rliesenfeld** [comment]
See #326

**Comment by OywpIrving** [comment]
Invalid mock-up for internal class
