### ISSUE TITLE
Mocked InputStream results in java.lang.StackOverflowError

### ISSUE THREAD

**Issue by MarkusLutum** [jmockit/jmockit1#364]
We just updated our tests from 1.18 to a self build 1.30 Version.
1.29 could not be used because it forbids Mocking our @Entity pojos.

The only Problem left is that We retrieve a StackOverflowError while mocking Streams. 
This worked before. Any suggestions?

Test to reproduce:
`@RunWith(JMockit.class)
public class CommandTest {
    
    @Mocked
    private InputStream in;
       
    @Test
    public void unknownCommandTestML() throws IOException {
        final char[] password = "1234".toCharArray();
        new StrictExpectations() {
            {
                // First password entry
                in.read(); result = password[0];
                in.read(); result = password[1];
                in.read(); result = password[2];
                in.read(); result = password[3];
                in.read(); result = '\n';
                // Retyped password
                in.read(); result = password[0];
                in.read(); result = password[1];
                in.read(); result = password[2];
                in.read(); result = password[3];
                in.read(); result = '\n';                
            }
        };
        // do tests here
    }
}`

Results in:
`java.lang.StackOverflowError
	at mockit.internal.expectations.mocking.MockedBridge.invoke(MockedBridge.java:39)
	at java.io.InputStream.<init>(InputStream.java)
	at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:694)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:360)
	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mockit.internal.expectations.mocking.MockedBridge.invoke(MockedBridge.java:39)
	at java.io.InputStream.<init>(InputStream.java)
	at java.util.zip.ZipFile$ZipFileInputStream.<init>(ZipFile.java:694)
	at java.util.zip.ZipFile.getInputStream(ZipFile.java:360)
	at java.util.jar.JarFile.getInputStream(JarFile.java:447)
	at sun.misc.URLClassPath$JarLoader$2.getInputStream(URLClassPath.java:940)
	at sun.misc.Resource.cachedInputStream(Resource.java:77)
	at sun.misc.Resource.getByteBuffer(Resource.java:160)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:454)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at mockit.internal.expectations.mocking.MockedBridge.invoke(MockedBridge.java:39)
.....`

**Comment by rliesenfeld** [comment]
Reproduced in JMockit 1.29. In 1.30 it's already fixed.

Note it's easier to write the test as follows:

```
    int[] password = {'1', '2', '3', '4', '\n'};

    new StrictExpectations() {{
         // First password entry
         in.read(); result = password;
         // Retyped password
         in.read(); result = password;
    }};
```
That said, mocking an `InputStream` is always a sure sign of over-mocking, though.

**Comment by MarkusLutum** [comment]
Not my Testcode, I just have to update :-)
But still I just tried it 5 Minutes ago after updating the last 2 commits. 
On my side it still fails if I use
```
@Mocked
private InputStream in;
```
I fixed it locally already with an own Input and OutputStream Implementation for this test.
