### ISSUE TITLE
Expectation with delegate matcher on linux (OpenJDK) fails, works on windows (Oracle JDK) - sample attached

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#421]
[TestHelloWorld.txt](https://github.com/jmockit/jmockit1/files/1036121/TestHelloWorld.txt)
Please provide the following information:

* Version of JMockit that was used: 

1.30
 
* Description of the problem:

Use of a customer matcher causes mock to become inoperative and a call on the real is made but only on linux and not on windows. With the any matcher all is ok on both Linux and Windows environments. Problem is just with the delegate.  The windows version runs under eclipse and the linux version runs under Intellij

Sample file that demonstrates the problem is attached. TestHelloWord

On windows with Oracle's JDK 1.8 all works fine. On windows with OpenJDK 1.8 all works fine.

On Linux CentOS with java-1.8.0-openjdk-1.8.0.131-2.b11.el7_3.x86_64 it fails
and tries to make the actual socket connect call (see attached sample code)

java.net.ConnectException: Connection refused (Connection refused)
                at java.net.PlainSocketImpl.socketConnect(Native Method)
                at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
                at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
                at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
                at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
                at java.net.Socket.connect(Socket.java:589)
                at java.net.Socket.connect(Socket.java:538)
                at testproblem.TestHelloWorld$UnitUnderTest.func(TestHelloWorld.java:36)
                at testproblem.TestHelloWorld.test(TestHelloWorld.java:80)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

* Please avoid reporting a problem that cannot be reproduced by project members.
Instead, include enough information (typically, an example test or more, perhaps accompanied by a
Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments.
Otherwise, there is a good chance the issue will be immediately closed with the "could not reproduce" tag.

* Also, avoid issues that fall outside the scope of the project. For example, attempting to use JMockit
APIs from Groovy or Scala code. Current project members are not going to add such support. If you would
like to contribute to the project in such areas, please submit Pull Requests.

**Comment by brucetrask** [comment]
Fixed it. My problem. Got "localhost" instead of "127.0.0.1". Should have know that.
