### ISSUE TITLE
Instantiating mocks with Spring injection

### ISSUE THREAD

**Issue by Davidside** [jmockit/jmockit1#441]
* Version of JMockit that was used: 1.33

* Description of the problem:
I am trying to use mocks with Wicket framework and spring injection. In wicket when some panel is created in production code, spring lazily initialize the service beans inside the panel annotated with @SpringBean. The same I am using in tests. The example test could look like this:

@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(loader=AnnotationConfigContextLoader.class)
public class TestCase {

      @Configuration
      static class ContextConfiguration {
           @Bean
            public ProfilesService profilesService() {
                 return profilesService = createMock();
            }
      }

       static ProfilesService profilesService;

	@Test
	public void testName() throws Exception {
                startSomePanel();
	}

With EasyMock or Mockito I am able to create mock inside context configuration and then use it in tests. But I am not able to create a mock in JMockit because it has only annotations for creating mocks. I am able to solve this with JMockit with couple of workarounds but not any of it is a clean way. For example I can create MockUp inside context config and then in the test use the @Capturing annotation, but that took a long time when I am running the tests. Also in context config I can return the real implementation of interface a then use @Mocked annotation in test, but that is not quite clean if I dont want to know anything about implemantations of services inside the test.

Is there any clean solution which I can use with JMockit, like with EasyMock or Mockito? 

Thanks in advance.
David.

**Comment by rliesenfeld** [comment]
Same solution as for #250 should apply here.

**Comment by Davidside** [comment]
Yeah I could solve this by @Capturing annotation, but it has two down sides. 

Firstly I dont want to create an anonnymous class of interface with empty methods in context config, because intefaces has a lots of methods. So I can use MockUp<T>() {}.getMockInstance(); instead, but this sometimes fails on NPE for some services. But this could be handled with different own solution like creating a mock from interface, the same way how EasyMock or Mockito do it.


Caused by: java.lang.NullPointerException
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:203)
	at com.sun.beans.TypeResolver.resolve(TypeResolver.java:218)
	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
	at java.beans.FeatureDescriptor.getParameterTypes(FeatureDescriptor.java:387)
	at java.beans.MethodDescriptor.setMethod(MethodDescriptor.java:114)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:72)
	at java.beans.MethodDescriptor.<init>(MethodDescriptor.java:56)
	at java.beans.Introspector.getTargetMethodInfo(Introspector.java:1149)
	at java.beans.Introspector.getBeanInfo(Introspector.java:416)
	at java.beans.Introspector.getBeanInfo(Introspector.java:163)
	at org.springframework.beans.CachedIntrospectionResults.<init>(CachedIntrospectionResults.java:224)
	at org.springframework.beans.CachedIntrospectionResults.forClass(CachedIntrospectionResults.java:149)
	at org.springframework.beans.BeanWrapperImpl.getCachedIntrospectionResults(BeanWrapperImpl.java:324)
	at org.springframework.beans.BeanWrapperImpl.getPropertyDescriptors(BeanWrapperImpl.java:331)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.filterPropertyDescriptorsForDependencyCheck(AbstractAutowireCapableBeanFactory.java:1242)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1101)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:517)
	... 36 more


Secondly (the bigger issue), when I use Capturing, running the test takes inadequate amount of time and it also grows linearly with every other Capturing annotation. It means when I dont use Capturing, it takes about a 1 second to run a test, when I use one Capturing annotation, it takes 7 seconds, when I use two Capturing it takes 14 seconds and so on. I need to write an integration test with 7 services, so it is not acceptable to take it so much time.
