### ISSUE TITLE
java.lang.LinkageError duplicate class definition... when running with coverage

### ISSUE THREAD

**Issue by brucetrask** [jmockit/jmockit1#488]
Please provide the following information:

* Version of JMockit that was used: 1.34

* Description of the problem: LinkageError when running with coverage

When I run my test without coverage it works. When I run the test with coverage I get a LinkageError.

java.lang.LinkageError: loader (instance of  sun/misc/Launcher$AppClassLoader): attempted  duplicate class definition for name: "com/company/proc/util/collections/AbstractList"
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.testpackage..TestList.test(TestList.java:11)

Not sure how to tackle this as it seems that the coverage code is complaining and not my normal runtime.

* Please avoid reporting a problem that cannot be reproduced by project members.
Instead, include enough information (typically, an example test or more, perhaps accompanied by a
Maven/Ant/Gradle build script) so that other developers can verify the problem in their own environments.

* Also, avoid issues that fall outside the scope of the project. For example, attempting to use JMockit
APIs from Groovy or Scala code. If you would like to contribute to the project in such areas, please submit
Pull Requests.

**Comment by rliesenfeld** [comment]
Please note the bullet item in the issue template saying to "avoid reporting a problem that cannot be reproduced by project members". (Also, that text in the issue template is supposed to be deleted before posting the issue.)
