### ISSUE TITLE
Verifying SLF4J logging passes for 1.33, fails for 1.34+

### ISSUE THREAD

**Issue by Thunderforge** [jmockit/jmockit1#507]
Library versions
----
* JMockit: 1.33, 1.34 through 1.38
* JUnit: 4.12
* [SLF4J ](https://www.slf4j.org/): slf4j-api:1.7.25, slf4j-log4j12:1.7.25

Description of the problem
----

Consider the following code, which uses an [SLF4J Logger](https://www.slf4j.org/api/org/slf4j/Logger.html):

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MyClass {

    private static final Logger LOGGER = LoggerFactory.getLogger(MyClass.class);

    public void logErrorMessage(String message) {
        LOGGER.error(message);
    }
}
```

This is unit tested like so, following the instructions on [this StackOverflow post](https://stackoverflow.com/a/40660763/531762):

```java
import mockit.Capturing;
import mockit.Tested;
import mockit.Verifications;
import org.junit.Test;
import org.slf4j.Logger;

public class MyClassTest {

    @Tested
    private MyClass myClass;

    @Capturing
    private Logger logger;

    @Test
    public void logErrorMessageSuccessful() {
        final String message = "Foo";
        myClass.logErrorMessage(message);

        new Verifications() {{
            logger.error(message);
        }};
    }
}
```

With JMockit 1.33, this unit test passes. With JMockit 1.34 and later, it fails with the following error:

```
Missing invocation to:
org.slf4j.Logger#error("Foo")
   on mock instance: org.slf4j.$Impl_Logger@2690d8e4
	at MyClassTest$1.<init>(MyClassTest.java:26)
	at MyClassTest.logErrorMessageSuccessful(MyClassTest.java:25)
```

This is reproducible 100% time on every version up to 1.38 (the latest at the time of this writing).

The issues fixed according to the [1.34 changelog](http://jmockit.github.io/changes.html#1.34) don't seem to be relevant to this problem, but it does include this item:

> * Improved @Capturing performance.

Is it possible that a regression was introduced as a result of those performance improvements?

**Comment by Thunderforge** [comment]
Did some more investigating and found that this only seems to happen if `slf4j-log4j12` is on the classpath. If you use do not have it (thus relying on the no-operation logger implementation) it passes.

Here is the Gradle dependency list I used for the tests above:

```groovy
dependencies {
    compile "org.slf4j:slf4j-api:1.7.25"
    compile "org.slf4j:slf4j-log4j12:1.7.25"
    testCompile "org.jmockit:jmockit:1.38"
    testCompile "junit:junit:4.12"
}
```
Commenting out the second line passes, but of course results in this error because no logging library is loaded.

```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```
