### ISSUE TITLE
NullPointerException when Spring Boot Starter Logging and Logback are on the class path with JMockit

### ISSUE THREAD

**Issue by Thunderforge** [jmockit/jmockit1#523]
Library versions
----
* JMockit: 1.39
* JUnit: 4.12
* [Spring Boot Starter Logging](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-logging/1.5.10.RELEASE): 1.5.10.RELEASE (includes SLF4J and Logback)

Description of the problem
----

JMockit and Spring Boot Starter Logging

Consider the following code, which uses an [SLF4J Logger](https://www.slf4j.org/api/org/slf4j/Logger.html):

```java
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MyClass {

    private static final Logger LOGGER = LoggerFactory.getLogger(MyClass.class);

    public void logErrorMessage(String message) {
        LOGGER.error(message);
    }
}
```

This is unit tested like so, following the instructions on [this StackOverflow post](https://stackoverflow.com/a/40660763/531762):

```java
import mockit.Capturing;
import mockit.Tested;
import mockit.Verifications;
import org.junit.Test;
import org.slf4j.Logger;

public class MyClassTest {

    @Tested
    private MyClass myClass;

    @Capturing
    private Logger logger;

    @Test
    public void logErrorMessageSuccessful() {
        final String message = "Foo";
        myClass.logErrorMessage(message);

        new Verifications() {{
            logger.error(message);
        }};
    }
}
```

If Spring Boot Starter Logging is also on the classpath, then the following error is printed in Standard Out, with the stack trace showing JMockit as part of it:

```
16:38:41,816 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@33:90 - RuntimeException in Action for tag [logger] java.lang.NullPointerException
	at java.lang.NullPointerException
	at 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at 	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:155)
	at 	at ch.qos.logback.classic.joran.action.LoggerAction.begin(LoggerAction.java:54)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBeginAction(Interpreter.java:269)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:145)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.startElement(Interpreter.java:128)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:50)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at 	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at 	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at 	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at 	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at 	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at 	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at 	at MyClass.<clinit>(MyClass.java:6)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at 	at mockit.internal.reflection.ConstructorReflection.invoke(ConstructorReflection.java:46)
	at 	at mockit.internal.injection.constructor.ConstructorInjection.invokeConstructor(ConstructorInjection.java:180)
	at 	at mockit.internal.injection.constructor.ConstructorInjection.instantiate(ConstructorInjection.java:71)
	at 	at mockit.internal.injection.TestedObjectCreation.create(TestedObjectCreation.java:68)
	at 	at mockit.internal.injection.TestedObject.createAndRegisterNewObject(TestedObject.java:127)
	at 	at mockit.internal.injection.TestedObject.instantiateWithInjectableValues(TestedObject.java:80)
	at 	at mockit.internal.injection.TestedClassInstantiations.instantiateTestedObject(TestedClassInstantiations.java:141)
	at 	at mockit.internal.injection.TestedClassInstantiations.assignNewInstancesToTestedFields(TestedClassInstantiations.java:134)
	at 	at mockit.integration.internal.TestRunnerDecorator.createInstancesForTestedFields(TestRunnerDecorator.java:181)
	at 	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.executeTestMethod(JUnit4TestRunnerDecorator.java:149)
	at 	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:70)
	at 	at mockit.integration.junit4.internal.FakeFrameworkMethod.invokeExplosively(FakeFrameworkMethod.java:34)
	at 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java)
	at 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at 	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at 	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at 	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at 	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at 	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

And ultimately, the test fails with this:

```
java.lang.ExceptionInInitializerError
Caused by: java.lang.NullPointerException
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:155)
	at ch.qos.logback.classic.LoggerContext.getLogger(LoggerContext.java:1)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at MyClass.<clinit>(MyClass.java:6)
```

This is reproducible 100% time on JMockit 1.39 (the latest at the time of this writing). [Here is a sample project](https://github.com/jmockit/jmockit1/files/2064246/JMockitTest.zip) where this is reproducible (run `gradlew build` on the command line to test). In the `build.gradle` file, there is a line that is commented out that excludes Logback. If that is uncommented, the test will pass.

This issue may be related to #507, which also involved SLF4J interacting

**Comment by rliesenfeld** [comment]
It's simply a consequence of what `@Capturing` does: it mocks *all* classes implementing the mocked (capturing) interface, which in this case includes `ch.qos.logback.classic.Logger`. Eventually (during logger creation by the logger factory) an instance of this logger (which is mocked) returns `null` from a method call, and this `null` is `put` into a `ConcurrentHashMap`, which does not accepts nulls, hence the NPE.

There is nothing JMockit can do to prevent such occurrences, without fundamentally changing the way that `@Capturing` does mocking. A "solution" here is to avoid `@Capturing`, and instead mock the `LoggerFactory`:

```
    @Mocked LoggerFactory mockLoggerFactory;
    @Mocked Logger logger;
```
