### ISSUE TITLE
JMockit on Java 11

### ISSUE THREAD

**Issue by risicle** [jmockit/jmockit1#534]
* Version of JMockit that was used: 

1.40

* Description of the problem:

This is a stub issue for JMockit on Java 11. I'll have a go at getting jmockit's test suite running on java 11 to see if that passes, but for now I seem to be getting:

```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost or NestMembers attribute
        at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
        at mypackage.MyTest$1.&lt;init&gt;(MyTest.java:52)
        ...
```

When instantiating a `MockUp` derivative that works fine on java <= 10.

**Comment by don-vip** [comment]
It seems related to [JEP 181: Nest-Based Access Control](http://openjdk.java.net/jeps/181)

**Comment by don-vip** [comment]
The embedded version of [ASM](https://asm.ow2.io/) must be upgraded to latest version (6.2).

**Comment by rliesenfeld** [comment]
Could you show the contents of `MyTest.java`?

**Comment by risicle** [comment]
For instance: https://github.com/openstreetmap/josm/blob/147ffea86b2232497745211db45bf48783bd91ef/test/unit/org/openstreetmap/josm/actions/ExitActionTest.java#L42

**Comment by don-vip** [comment]
why did you delete my comments?

**Comment by risicle** [comment]
Also curious why my colleague's diagnosis was deleted...?

**Comment by rliesenfeld** [comment]
Support for the new "NestHost" and "NestMembers" classfile attributes will be added once JDK 11 is released.

**Comment by rliesenfeld** [comment]
I tested it with a simple test which applies an anonymous MockUp to a small class, but there is no failure (compiling with "-source 1.11" and "-target 1.11").

**Comment by don-vip** [comment]
I don't remember the example ris gave you (_please stop deleting all comments, this is annoying and unproductive_) but all our tests using JMockit are failing with Java 11 and 12.

We compile tests in 1.8 mode with `ant` [as follows](https://github.com/openstreetmap/josm/blob/mirror/build.xml#L454):
```xml
<property name="java.lang.version" value="1.8" />
<javac srcdir="${test.dir}/@{testfamily}" destdir="${test.dir}/build/@{testfamily}"
    target="${java.lang.version}" source="${java.lang.version}" debug="on"
    includeantruntime="false" createMissingPackageInfoClass="false" encoding="UTF-8">
    <compilerarg value="-Xlint:all"/>
    <compilerarg value="-Xlint:-serial"/>
    <classpath>
        <cp-elements/>
    </classpath>
</javac>
```

To ignore this issue we're using right now this [workaround](https://github.com/openstreetmap/josm/blob/mirror/test/unit/org/openstreetmap/josm/TestUtils.java#L415). If I disable it and run `org.openstreetmap.josm.gui.preferences.advanced.ExportProfileActionTest` from Eclipse, using `-javaagent:test/lib/jmockit-1.41.jar`, it works with Java 10.0.2, but fails with Java 11 (b28):
```
java.lang.UnsupportedOperationException: class redefinition failed: attempted to change the class NestHost or NestMembers attribute
	at java.instrument/sun.instrument.InstrumentationImpl.redefineClasses0(Native Method)
	at org.openstreetmap.josm.testutils.mockers.BaseDialogMockUp.<init>(BaseDialogMockUp.java:47)
	at org.openstreetmap.josm.testutils.mockers.JOptionPaneSimpleMocker.<init>(JOptionPaneSimpleMocker.java:114)
	at org.openstreetmap.josm.testutils.mockers.JOptionPaneSimpleMocker.<init>(JOptionPaneSimpleMocker.java:99)
	at org.openstreetmap.josm.gui.preferences.advanced.ExportProfileActionTest.testAction(ExportProfileActionTest.java:34)
	at org.openstreetmap.josm.testutils.JOSMTestRules$TimeoutThread.run(JOSMTestRules.java:700)
```
Here's the test:
```java
public class ExportProfileActionTest {
    @Rule
    public JOSMTestRules test = new JOSMTestRules().preferences().assertionsInEDT();

    @Test
    public void testAction() {
        TestUtils.assumeWorkingJMockit();
        new JOptionPaneSimpleMocker(ImmutableMap.of(
            "All the preferences of this group are default, nothing to save", JOptionPane.OK_OPTION
        ));
        new ExportProfileAction(Preferences.main(), "foo", "bar").actionPerformed(null);
        new ExportProfileAction(Preferences.main(), "expert", "expert").actionPerformed(null);
    }
}
```
Our mockers can be found [here](https://github.com/openstreetmap/josm/tree/mirror/test/unit/org/openstreetmap/josm/testutils/mockers).

**Comment by rliesenfeld** [comment]
Please... show a small, self-contained example test, or don't bother.
