### ISSUE TITLE
Exception in TestNg setUp method causes NPE 

### ISSUE THREAD

**Issue by dasAnderl** [jmockit/jmockit1#536]
Please provide the following information:

* Version of JMockit that was used: Jmockit 1.40, TestNg 6.14.3, Java 1.8

* Description of the problem: When an exception is thrown in a setup method (@BeforeMethod or @BeforeClass testNg annotations) a NPE occurs: 

`java.lang.NullPointerException
	at mockit.integration.testng.TestNGRunnerDecorator.beforeInvocation(TestNGRunnerDecorator.java:126)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:493)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:533)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)`

This is a big problem since the generated test report, now contains 2 entries for 1 test, 1 failed and one skipped:

skipped: seat.mod.testing.business.jenkins.InstalledBaseUploadJenkinsTest#uploadInstalledBase
failed: seat.mod.testing.business.jenkins.InstalledBaseUploadJenkinsTest#uploadInstalledBase (1)

The test:

`public class InstalledBaseUploadJenkinsTest {

        @BeforeClass
	public void setUp() {
		throw new RunTimeException("");
	}

	@Test
	public void uploadInstalledBase() {}`

**Comment by rliesenfeld** [comment]
After some debugging, I found out it's actually a TestNG bug.
The test class below demonstrates it (with no jmockit jar in the classpath):

```
import org.testng.annotations.*;
import org.testng.*;

// Run with "-listener ListenerTest"
public class ListenerTest implements IInvokedMethodListener {
   @Override
   public void beforeInvocation(IInvokedMethod method, ITestResult testResult) {
      IClass testClass = testResult.getTestClass(); // this should never be null...
      testClass.getRealClass(); // ... but it is after setUp(), resulting in an NPE
   }

   @Override public void afterInvocation(IInvokedMethod method, ITestResult testResult) {}

   @BeforeClass // also happens with @BeforeMethod and @BeforeTest
   public void setUp() { throw new RuntimeException(); }

   @Test public void anyTest() {}
}
```

**Comment by dasAnderl** [comment]
firstly, thank you for ur very quick response. i just setup setup a quick empty mvn project with testng 6.14.3 and executed the test i posted. the result is exactly what it should be:

- setup method marked as failure
- uploadInstalledBase marked as skipped

this is not the behaviour when jmockit is on the classpath:

- setup method marked as failure
- uploadInstalledBase marked as skipped
- uploadInstalledBase (1) marked as failure -> because of this npe

it might be the case that u excpect testNg to always have testResult.getTestClass() available, but this just shows that it is no the case.
if id go to testNg and submit a bug, i guess they will tell me, that there is no problem if jmockit is not on the classpath, which is true. so in my opinion this a testng bug.

**Comment by rliesenfeld** [comment]
Yes, I understand that your test fails with JMockit in the classpath, but not without. But it's not due to anything wrong that JMockit is doing. It only happens because JMockit makes (legitimate) use of TestNG's `IInvokedMethodListener` feature, but said feature is broken in TestNG.

I even noticed where exactly the bug is in TestNG's implementation: at `org.testng.internal.Invoker#invokeMethod`, line 513, where it erroneously calls `new TestResult()` instead of using one of the constructors which take the `IClass testClass` object (which is passed in to `invokeMethod`). So, the bug is that TestNG is creating an uninitialized `TestResult`, which never gets initialized later, as `init(testClass, ...)` doesn't get called (as a consequence of the exception thrown in the `@BeforeClass` method).

**Comment by dasAnderl** [comment]
testng replied very quickly in version 7.0.0-SNAPSHOT the error is gone
