### ISSUE TITLE
@Injectable String method parameters now cause NPEs when run from gradle

### ISSUE THREAD

**Issue by lstreepy** [jmockit/jmockit1#560]
Please provide the following information:

* Version of JMockit that was used: 
JMockit 1.37
Gradle 4.8
JVM: 1.8.0_152 (Oracle Corporation 25.152-b16)
OS: Windows 7 6.1 amd64
TestNG: 6.8

* Description of the problem:

Using an @Injectable String as a test method argument causes an NPE (under gradle):
```
  Gradle suite > Gradle test > reproducer.InjectableStringTests.testInjectableStrings[0] FAILED
  org.gradle.api.internal.tasks.testing.testng.UnrepresentableParameterException
      Caused by: java.lang.NullPointerException

  And, from the test report, this more complete stack trace shows:

  Caused by: java.lang.NullPointerException
     at java.lang.String.length(String.java:623)
     at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:447)
     at java.lang.StringBuilder.append(StringBuilder.java:136)
     at org.gradle.api.internal.tasks.testing.testng.TestNGTestResultProcessorAdapter.calculateTestCaseName(TestNGTestResultProcessorAdapter.java:193)
```

This is a regression, as it worked in version 1.21.

Reproducer:
```java
package reproducer;

import mockit.Injectable;
import org.testng.Assert;
import org.testng.annotations.Test;

public class InjectableStringTests
{
    @Test
    public void testInjectableStrings(@Injectable("abc") String s1)
    {
        Assert.assertEquals(s1, "abc");
    }
}
```

**Comment by rliesenfeld** [comment]
It happens on 1.37, but this test is no longer possible (in this exact form) on version 1.42+.
The equivalent would be:
```
public class InjectableStringTests
{
   @Injectable String s1 = "abc";

   @Test
   public void testInjectableStrings() {
      Assert.assertEquals(s1, "abc");
   }
}
```
... which works fine on TestNG 6.8.21.
