### ISSUE TITLE
Junit 5 Parallel Execution causes test failures

### ISSUE THREAD

**Issue by djwoodward** [jmockit/jmockit1#579]
Please provide the following information:

* Version of JMockit that was used: 
Jmockit 1.44
Junit 5.3.2

* Description of the problem:

junit.jupiter.execution.parallel.enabled=true

Using Junit 5's built in parallel execution causes test failures. 

```
java.lang.IllegalArgumentException: No instance field of name "this$0" found in class TestA

	at mockit.internal.reflection.FieldReflection.getDeclaredField(FieldReflection.java:38)
	at mockit.internal.reflection.FieldReflection.setFieldValue(FieldReflection.java:176)
	at mockit.internal.injection.TestedField.setInstance(TestedField.java:56)
	at mockit.internal.injection.TestedObject.createAndRegisterNewObject(TestedObject.java:128)
	at mockit.internal.injection.TestedObject.instantiateWithInjectableValues(TestedObject.java:80)
	at mockit.internal.injection.TestedClassInstantiations.instantiateTestedObject(TestedClassInstantiations.java:150)
	at mockit.internal.injection.TestedClassInstantiations.assignNewInstancesToTestedFieldsFromBaseClasses(TestedClassInstantiations.java:124)
	at mockit.integration.TestRunnerDecorator.createInstancesForTestedFieldsFromBaseClasses(TestRunnerDecorator.java:167)
	at mockit.integration.junit5.JMockitExtension.beforeTestExecution(JMockitExtension.java:95)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeBeforeTestExecutionCallbacks$4(TestMethodTestDescriptor.java:142)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:156)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeTestExecutionCallbacks(TestMethodTestDescriptor.java:141)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:112)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:147)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:121)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:170)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Test:
```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

import mockit.Tested;

public class TestA {
	@Tested
	private Service service;

	@Test
	public void method1() throws InterruptedException {
		assertEquals(1 + 2, service.add(1, 2));
		Thread.sleep(1000);
	}

	@Test
	public void method2() throws InterruptedException {
		assertEquals(1 + 2, service.add(1, 2));
		Thread.sleep(1000);

	}

	@Test
	public void method3() throws InterruptedException {
		assertEquals(1 + 2, service.add(1, 2));
		Thread.sleep(1000);
	}
}
```

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [ ] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
Same as #408.
