### ISSUE TITLE
UnsatisfiedLinkError when trying to use System.currentTimeMillis()

### ISSUE THREAD

**Issue by budducci** [jmockit/jmockit1#583]
Please provide the following information:

* Version of JMockit that was used: 1.43

* Description of the problem:
Using Java 8 with JUnit 4.12 and Gradle.

The following stack trace is returned when running tests that execute System.currentTimeMillis() either explicitly or within native Java libraries. I am unable to provide the code which generates this error because of privacy concerns of my client.

I've been unable to find any relevant troubleshooting online.

java.lang.UnsatisfiedLinkError: java.lang.System.currentTimeMillis()J
	at java.lang.System.currentTimeMillis(Unknown Source)
	at java.io.ExpiringCache.put(ExpiringCache.java:94)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:429)
	at java.io.File.getCanonicalPath(File.java:618)
	at java.io.FilePermission$1.run(FilePermission.java:215)
	at java.io.FilePermission$1.run(FilePermission.java:203)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.io.FilePermission.init(FilePermission.java:203)
	at java.io.FilePermission.<init>(FilePermission.java:277)
	at sun.net.www.protocol.file.FileURLConnection.getPermission(FileURLConnection.java:228)
	at java.net.URLClassLoader.getPermissions(URLClassLoader.java:663)
	at sun.misc.Launcher$AppClassLoader.getPermissions(Launcher.java:346)
	at java.security.SecureClassLoader.getProtectionDomain(SecureClassLoader.java:206)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at sun.reflect.GeneratedSerializationConstructorAccessor26.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at mockit.internal.expectations.mocking.InstanceFactory.newUninitializedConcreteClassInstance(InstanceFactory.java:43)
	at mockit.internal.expectations.mocking.InstanceFactory$ClassInstanceFactory.create(InstanceFactory.java:90)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.assignNewInstanceToMockField(FieldTypeRedefinitions.java:139)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.createAndAssignNewInstances(FieldTypeRedefinitions.java:124)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.assignNewInstancesToMockFields(FieldTypeRedefinitions.java:115)
	at mockit.integration.TestRunnerDecorator.handleMockFieldsForWholeTestClass(TestRunnerDecorator.java:156)
	at mockit.integration.TestRunnerDecorator.updateTestClassState(TestRunnerDecorator.java:40)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.handleMockingOutsideTestMethods(JUnit4TestRunnerDecorator.java:129)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:37)
	at mockit.integration.junit4.FakeFrameworkMethod.invokeExplosively(FakeFrameworkMethod.java:29)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)

* Check that:

 - [ ] The problem can be reproduced by JMockit project members.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.

 - [x] The issue does not fall outside the scope of the project (for example, attempting to use JMockit
  APIs from Groovy or Scala code, or with an Android runtime).

 - [x] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
There is an answer in stackoverflow already, nothing to add.
