### ISSUE TITLE
non-static <clinit> methods generated

### ISSUE THREAD

**Issue by Vampire** [jmockit/jmockit1#590]
JMockit 1.44 generates a non-static `<clinit>` method when trying to generate a concrete subclass for an abstract type.
This then manifests as
```
Caused by: java.lang.ClassFormatError: Method <clinit> is not static in class file de/empic/web/core/api/$Subclass_AbstractApiClient_defaultApiClient
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:877)
	at mockit.internal.classGeneration.ImplementationClass$1.findClass(ImplementationClass.java:60)
	at mockit.internal.classGeneration.ImplementationClass.defineNewClass(ImplementationClass.java:62)
	at mockit.internal.classGeneration.ImplementationClass.generateClass(ImplementationClass.java:40)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.generateConcreteSubclassForAbstractType(BaseTypeRedefinition.java:300)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.createInstanceFactory(BaseTypeRedefinition.java:261)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineTargetClassAndCreateInstanceFactory(BaseTypeRedefinition.java:249)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineType(BaseTypeRedefinition.java:68)
	at mockit.internal.expectations.mocking.TypeRedefinition.redefineType(TypeRedefinition.java:28)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldType(FieldTypeRedefinitions.java:78)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldType(FieldTypeRedefinitions.java:65)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldTypes(FieldTypeRedefinitions.java:53)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.<init>(FieldTypeRedefinitions.java:33)
	at mockit.integration.TestRunnerDecorator.handleMockFieldsForWholeTestClass(TestRunnerDecorator.java:142)
	at mockit.integration.TestRunnerDecorator.updateTestClassState(TestRunnerDecorator.java:40)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.handleMockingOutsideTestMethods(JUnit4TestRunnerDecorator.java:129)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:37)
	at mockit.integration.junit4.FakeFrameworkMethod.invokeExplosively(FakeFrameworkMethod.java:29)
	...
```

The source of the non-static `<clinit>` is the line `mw = cw.visitMethod(Access.PUBLIC, name, desc, signature, exceptions);` in `mockit.internal.expectations.mocking.SubclassGenerationModifier#generateMethodImplementation` with this stack trace:

```
	at mockit.internal.expectations.mocking.SubclassGenerationModifier.generateMethodImplementation(SubclassGenerationModifier.java:32)
	at mockit.internal.classGeneration.BaseSubclassGenerator.generateImplementationForInterfaceMethodIfMissing(BaseSubclassGenerator.java:180)
	at mockit.internal.classGeneration.BaseSubclassGenerator.generateImplementationsForAbstractMethods(BaseSubclassGenerator.java:162)
	at mockit.internal.classGeneration.BaseSubclassGenerator.visitEnd(BaseSubclassGenerator.java:136)
	at mockit.asm.classes.ClassReader.accept(ClassReader.java:116)
	at mockit.asm.classes.ClassReader.accept(ClassReader.java:93)
	at mockit.internal.classGeneration.ImplementationClass.generateClass(ImplementationClass.java:38)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.generateConcreteSubclassForAbstractType(BaseTypeRedefinition.java:300)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.createInstanceFactory(BaseTypeRedefinition.java:261)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineTargetClassAndCreateInstanceFactory(BaseTypeRedefinition.java:249)
	at mockit.internal.expectations.mocking.BaseTypeRedefinition.redefineType(BaseTypeRedefinition.java:68)
	at mockit.internal.expectations.mocking.TypeRedefinition.redefineType(TypeRedefinition.java:28)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldType(FieldTypeRedefinitions.java:78)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldType(FieldTypeRedefinitions.java:65)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.redefineFieldTypes(FieldTypeRedefinitions.java:53)
	at mockit.internal.expectations.mocking.FieldTypeRedefinitions.<init>(FieldTypeRedefinitions.java:33)
	at mockit.integration.TestRunnerDecorator.handleMockFieldsForWholeTestClass(TestRunnerDecorator.java:142)
	at mockit.integration.TestRunnerDecorator.updateTestClassState(TestRunnerDecorator.java:40)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.handleMockingOutsideTestMethods(JUnit4TestRunnerDecorator.java:129)
	at mockit.integration.junit4.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:37)
	at mockit.integration.junit4.FakeFrameworkMethod.invokeExplosively(FakeFrameworkMethod.java:29)
	...
```

**Comment by Vampire** [comment]
While trying to spin up a small reproducer, I found what the problem is and that it is even worse.

Here the reproducer:
_File `AbstractFoo.java`:_
```java
package sample;

public abstract class AbstractFoo implements Foo {
}

interface Foo {
    Object foo = new Object();
    static void foo() { }
    default void bar() { }
}
```
_File `ExampleTest.java`:_
```java
package sample;

import mockit.Mocked;
import org.junit.Test;

public class ExampleTest {
    @Mocked AbstractFoo foo;

    @Test
    public final void test() {
    }
}
```
The interface Foo has three methods that either cannot, should not or do not have to be overwritten by implementors.
- the static implicit `<clinit>` method that initializes the field `foo`,
- the static method `foo` and
- the default method `bar`

If you debug this execution, you will see that in `mockit.internal.classGeneration.BaseSubclassGenerator#generateImplementationForInterfaceMethodIfMissing` `generateMethodImplementation` gets called three times while it should not be called at all.

As far as I can tell, the code should exclude methods with `static` modifier which will fix the first two points and additionally exclude methods that have a default implementation in the interface to fix the third case.
