### ISSUE TITLE
Unable to inject @Mocked parameters with TestNG

### ISSUE THREAD

**Issue by archer920** [jmockit/jmockit1#595]
Please provide the following information:

* Version of JMockit that was used: 
JMockit 1.45
TestNG 6.4.13
Java 12
* Description of the problem:
Unit tests with TestNG fail when using @Mocked parameters. Here is an example test with output.
`
import mockit.Mocked;
import org.testng.annotations.Test;

public class Example {

    @Test
    public void example(@Mocked Runnable run) {
        System.out.println(run);
    }
}

`
Running this test produces the following output
`[Utils] [ERROR] [Error] org.testng.TestNGException: 
Cannot inject @Test annotated Method [example] with [interface java.lang.Runnable].
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
	at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:407)
	at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:356)
	at org.testng.internal.Parameters.createParameters(Parameters.java:635)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:769)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:914)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.runSuites(TestNG.java:1028)
	at org.testng.TestNG.run(TestNG.java:996)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)`

I do want to note that while I used Runnable in the example, the issue affects every class in my project. I get the same output regardless which class or classes I use in the parameters.

**Comment by rliesenfeld** [comment]
Yes, they are not supported on TesrNG. See release notes for version 1.42.
