### ISSUE TITLE
When I use coverage a NullPointException occured

### ISSUE THREAD

**Issue by RobertoHuang** [jmockit/jmockit1#621]
Hi

My Project git url is:git@github.com:RobertoHuang/RGP-DREAM-T.git

when i use mvn test, i got the following error:

java.lang.NullPointerException
	at mockit.coverage.modification.ClassModification.redefineClassesAlreadyLoadedForCoverage(ClassModification.java:35)
	at mockit.coverage.modification.ClassModification.<init>(ClassModification.java:27)
	at mockit.coverage.CodeCoverage.<init>(CodeCoverage.java:37)
	at mockit.coverage.CodeCoverage.create(CodeCoverage.java:71)
	at mockit.internal.startup.Startup.activateCodeCoverageIfRequested(Startup.java:68)
	at mockit.internal.startup.Startup.premain(Startup.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:386)
	at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:401)

**Comment by rliesenfeld** [comment]
Does not happen for me. Which JDK are you using? And which version of Maven?

**Comment by RobertoHuang** [comment]
with JDK1.8 Maven3.2.5
And when i set jmockit.version to 1.36 the error fixed，but jmockit.version 1.47 the error happend

**Comment by rliesenfeld** [comment]
Strangely, the NPE should be occurring for me, I don't know why it doesn't. Anyway, the "-javaagent" line in the pom.xml should not end with "=coverage".

Also, the use of "<systemPropertyVariables>" gets ignored by Surefire when "<argLine>" is also specified. They must be put into "<argLine>" as well - I already fixed the documentation in the Tutorial about this.
