### ISSUE TITLE
Jmockit 1.8 version Campatibility issue with JDK 11

### ISSUE THREAD

**Issue by MumtazRashid** [jmockit/jmockit1#632]
I was using 1.8 version of jmockit with jdk 8, it was working fine but when i upgraded jdkto version 11 it is throwing below error :  

Caused by: java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:23)
	at mockit.internal.startup.Startup.verifyInitialization(Startup.java:213)
	at mockit.MockUp.<clinit>(MockUp.java:88)
	... 2 more

Root cause: java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:23)
	at mockit.internal.startup.Startup.verifyInitialization(Startup.java:213)
	at mockit.MockUp.<clinit>(MockUp.java:88)

How can we resolve it ?

**Comment by rliesenfeld** [comment]
The only way to resolve it is to use a newer version of JMockit, if 1.8 doesn't recognize Java 11.
