### ISSUE TITLE
Incompatibilty with Intellij IDEA 2019.3 - StackOverflowError

### ISSUE THREAD

**Issue by simon-jlc** [jmockit/jmockit1#642]
### Versions

* Version of JMockit that was used:  1.46
* Intellij IDEA's version :
Build #IU-193.5233.102, built on November 27, 2019
Runtime version: 11.0.4+10-b520.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

* Project Java's version:  
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
* JUnit's version : 4.12

### Reproduction scenario

* Write a basic simple unit test (without any reference to JMockit API)
* Configure a JUnit launcher and add jmockit agent -javaagent:${MAVEN_REPO}/org/jmockit/jmockit/1.46/jmockit-1.46.jar
* Launch unit test via JUnit launcher, then you'll get Stack

```
Exception in thread "main" java.lang.StackOverflowError
       at java.base/java.lang.System.checkKey(System.java:939)
       at java.base/java.lang.System.getProperty(System.java:842)
       at mockit.coverage.Configuration.getProperty(Configuration.java:21)
       at mockit.coverage.Configuration.getProperty(Configuration.java:17)
       at mockit.coverage.CodeCoverage.active(CodeCoverage.java:61)
       at mockit.integration.junit4.FakeRunNotifier.fireTestRunStarted(FakeRunNotifier.java:31)
       at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java)
       at mockit.integration.junit4.FakeRunNotifier.fireTestRunStarted(FakeRunNotifier.java:36)
       at org.junit.runner.notification.RunNotifier.fireTestRunStarted(RunNotifier.java)
```

* Check the following:

 - [ ] If a defect or unexpected result, JMockit project members should be able to reproduce it.
  For that, include an example test (perhaps accompanied by a Maven/Gradle build script) which
  can be executed without changes and reproduces the failure.
 - [ ] If an enhancement or new feature request, it should be justified by an example test
 - [ ] demonstrating the validity and usefulness of the desired enhancement or new feature.
 - [x] The issue does not fall outside the scope of the project (for example, attempting to use
  JMockit APIs from Groovy or Scala code, or with an Android runtime).
 - [ ] The JDK where the problem occurs is a final release, not a development build.

**Comment by rliesenfeld** [comment]
Does it also happen with JMockit 1.48? I am currently using IntelliJ 2019.3 and JMockit.

**Comment by ens121** [comment]
Same thing happens to me with IntelliJ 2019.3 and JMockit 1.44 as well as 1.49 under AdoptOpenJDK 11.0.1.
