### ISSUE TITLE
IllegalStateException: JMockit requires a Java 6+ VM 	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile

### ISSUE THREAD

**Issue by milossesic** [jmockit/jmockit1#646]
- ant version 1.10.6
- junit version 4.12
- jmockit version 1.9 
- openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Zulu11.35+13-CA (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.35+13-CA (build 11.0.5+10-LTS, mixed mode)

Getting below stack trace with java 11 environment. the same setup works fine for jdk8 (tests pass).

java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:23)
	at mockit.internal.startup.Startup.initializeIfPossible(Startup.java:252)
	at mockit.integration.junit4.JMockit.<clinit>(JMockit.java:21)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.junit.runners.Suite.<init>(Suite.java:70)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

**Comment by rliesenfeld** [comment]
You will have to use a newer version of JMockit, I suppose.

**Comment by realduke2000** [comment]
I get the same issue

"/Applications/IntelliJ IDEA CE.app/Contents/jbr/Contents/Home/bin/java" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=54333:/Applications/IntelliJ IDEA CE.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath "/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/testng-plugin.jar:/Users/allen.hou/src/stash/nba/dbshares/server/target/test-classes:/Users/allen.hou/src/stash/nba/dbshares/server/target/classes:/Users/allen.hou/.m2/repository/org/testng/testng/6.9.10/testng-6.9.10.jar:/Users/allen.hou/.m2/repository/com/beust/jcommander/1.48/jcommander-1.48.jar:/Users/allen.hou/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar:/Users/allen.hou/.m2/repository/org/springframework/security/oauth/spring-security-oauth2/2.5.1.RELEASE/spring-security-oauth2-2.5.1.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-beans/5.3.13/spring-beans-5.3.13.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-core/5.3.13/spring-core-5.3.13.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-jcl/5.2.9.RELEASE/spring-jcl-5.2.9.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-context/5.3.13/spring-context-5.3.13.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-webmvc/5.3.13/spring-webmvc-5.3.13.jar:/Users/allen.hou/.m2/repository/org/jmockit/jmockit/1.13/jmockit-1.13.jar:/Users/allen.hou/.m2/repository/com/jayway/jsonpath/json-path/2.5.0/json-path-2.5.0.jar:/Users/allen.hou/.m2/repository/org/slf4j/slf4j-api/1.7.30/slf4j-api-1.7.30.jar:/Users/allen.hou/src/stash/nba/dbshares/model/target/classes:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-json-org/2.10.5/jackson-datatype-json-org-2.10.5.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.11.4/jackson-core-2.11.4.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.11.4/jackson-databind-2.11.4.jar:/Users/allen.hou/.m2/repository/org/json/json/20180813/json-20180813.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter/2.2.10.RELEASE/spring-boot-starter-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot/2.2.10.RELEASE/spring-boot-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.2.10.RELEASE/spring-boot-autoconfigure-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-logging/2.2.10.RELEASE/spring-boot-starter-logging-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/ch/qos/logback/logback-classic/1.2.7/logback-classic-1.2.7.jar:/Users/allen.hou/.m2/repository/ch/qos/logback/logback-core/1.2.7/logback-core-1.2.7.jar:/Users/allen.hou/.m2/repository/org/apache/logging/log4j/log4j-to-slf4j/2.17.0/log4j-to-slf4j-2.17.0.jar:/Users/allen.hou/.m2/repository/org/apache/logging/log4j/log4j-api/2.17.0/log4j-api-2.17.0.jar:/Users/allen.hou/.m2/repository/org/slf4j/jul-to-slf4j/1.7.30/jul-to-slf4j-1.7.30.jar:/Users/allen.hou/.m2/repository/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/Users/allen.hou/src/stash/nba/dbshares/storage/target/classes:/Users/allen.hou/.m2/repository/com/veritas/appliance/localization/1.0.105/localization-1.0.105.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-web/2.2.10.RELEASE/spring-boot-starter-web-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-json/2.2.10.RELEASE/spring-boot-starter-json-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jdk8/2.10.5/jackson-datatype-jdk8-2.10.5.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.10.5/jackson-datatype-jsr310-2.10.5.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/module/jackson-module-parameter-names/2.10.5/jackson-module-parameter-names-2.10.5.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-validation/2.2.10.RELEASE/spring-boot-starter-validation-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-web/5.3.13/spring-web-5.3.13.jar:/Users/allen.hou/.m2/repository/org/hibernate/validator/hibernate-validator/6.1.5.Final/hibernate-validator-6.1.5.Final.jar:/Users/allen.hou/.m2/repository/jakarta/validation/jakarta.validation-api/2.0.2/jakarta.validation-api-2.0.2.jar:/Users/allen.hou/.m2/repository/org/jboss/logging/jboss-logging/3.4.1.Final/jboss-logging-3.4.1.Final.jar:/Users/allen.hou/.m2/repository/com/fasterxml/classmate/1.5.1/classmate-1.5.1.jar:/Users/allen.hou/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:/Users/allen.hou/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:/Users/allen.hou/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/Users/allen.hou/.m2/repository/org/yaml/snakeyaml/1.26/snakeyaml-1.26.jar:/Users/allen.hou/.m2/repository/commons-codec/commons-codec/1.15/commons-codec-1.15.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-tomcat/2.2.10.RELEASE/spring-boot-starter-tomcat-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/Users/allen.hou/.m2/repository/org/apache/tomcat/embed/tomcat-embed-core/9.0.38/tomcat-embed-core-9.0.38.jar:/Users/allen.hou/.m2/repository/org/apache/tomcat/embed/tomcat-embed-el/9.0.38/tomcat-embed-el-9.0.38.jar:/Users/allen.hou/.m2/repository/org/apache/tomcat/embed/tomcat-embed-websocket/9.0.38/tomcat-embed-websocket-9.0.38.jar:/Users/allen.hou/.m2/repository/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar:/Users/allen.hou/.m2/repository/javax/activation/javax.activation-api/1.2.0/javax.activation-api-1.2.0.jar:/Users/allen.hou/.m2/repository/com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar:/Users/allen.hou/.m2/repository/com/sun/xml/bind/jaxb-impl/2.3.2/jaxb-impl-2.3.2.jar:/Users/allen.hou/.m2/repository/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-amqp/2.2.10.RELEASE/spring-boot-starter-amqp-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-messaging/5.2.9.RELEASE/spring-messaging-5.2.9.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/amqp/spring-rabbit/2.2.11.RELEASE/spring-rabbit-2.2.11.RELEASE.jar:/Users/allen.hou/.m2/repository/com/rabbitmq/amqp-client/5.7.3/amqp-client-5.7.3.jar:/Users/allen.hou/.m2/repository/org/springframework/amqp/spring-amqp/2.2.11.RELEASE/spring-amqp-2.2.11.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/retry/spring-retry/1.2.5.RELEASE/spring-retry-1.2.5.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-test/2.2.10.RELEASE/spring-boot-starter-test-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-test/2.2.10.RELEASE/spring-boot-test-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-test-autoconfigure/2.2.10.RELEASE/spring-boot-test-autoconfigure-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/jakarta/xml/bind/jakarta.xml.bind-api/2.3.3/jakarta.xml.bind-api-2.3.3.jar:/Users/allen.hou/.m2/repository/org/junit/jupiter/junit-jupiter/5.5.2/junit-jupiter-5.5.2.jar:/Users/allen.hou/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.5.2/junit-jupiter-api-5.5.2.jar:/Users/allen.hou/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/Users/allen.hou/.m2/repository/org/junit/platform/junit-platform-commons/1.5.2/junit-platform-commons-1.5.2.jar:/Users/allen.hou/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.5.2/junit-jupiter-params-5.5.2.jar:/Users/allen.hou/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.5.2/junit-jupiter-engine-5.5.2.jar:/Users/allen.hou/.m2/repository/org/junit/vintage/junit-vintage-engine/5.5.2/junit-vintage-engine-5.5.2.jar:/Users/allen.hou/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/Users/allen.hou/.m2/repository/org/junit/platform/junit-platform-engine/1.5.2/junit-platform-engine-1.5.2.jar:/Users/allen.hou/.m2/repository/junit/junit/4.12/junit-4.12.jar:/Users/allen.hou/.m2/repository/org/mockito/mockito-junit-jupiter/3.1.0/mockito-junit-jupiter-3.1.0.jar:/Users/allen.hou/.m2/repository/org/assertj/assertj-core/3.13.2/assertj-core-3.13.2.jar:/Users/allen.hou/.m2/repository/org/hamcrest/hamcrest/2.1/hamcrest-2.1.jar:/Users/allen.hou/.m2/repository/org/mockito/mockito-core/3.1.0/mockito-core-3.1.0.jar:/Users/allen.hou/.m2/repository/net/bytebuddy/byte-buddy/1.10.14/byte-buddy-1.10.14.jar:/Users/allen.hou/.m2/repository/net/bytebuddy/byte-buddy-agent/1.10.14/byte-buddy-agent-1.10.14.jar:/Users/allen.hou/.m2/repository/org/objenesis/objenesis/2.6/objenesis-2.6.jar:/Users/allen.hou/.m2/repository/org/skyscreamer/jsonassert/1.5.0/jsonassert-1.5.0.jar:/Users/allen.hou/.m2/repository/com/vaadin/external/google/android-json/0.0.20131108.vaadin1/android-json-0.0.20131108.vaadin1.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-test/5.3.13/spring-test-5.3.13.jar:/Users/allen.hou/.m2/repository/org/xmlunit/xmlunit-core/2.6.4/xmlunit-core-2.6.4.jar:/Users/allen.hou/.m2/repository/commons-io/commons-io/2.8.0/commons-io-2.8.0.jar:/Users/allen.hou/.m2/repository/org/springframework/boot/spring-boot-starter-security/2.2.10.RELEASE/spring-boot-starter-security-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-aop/5.3.13/spring-aop-5.3.13.jar:/Users/allen.hou/.m2/repository/org/springframework/security/spring-security-config/5.5.2/spring-security-config-5.5.2.jar:/Users/allen.hou/.m2/repository/org/springframework/security/spring-security-web/5.5.2/spring-security-web-5.5.2.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-expression/5.3.13/spring-expression-5.3.13.jar:/Users/allen.hou/.m2/repository/org/springframework/security/spring-security-core/5.5.2/spring-security-core-5.5.2.jar:/Users/allen.hou/.m2/repository/org/springframework/security/spring-security-crypto/5.2.6.RELEASE/spring-security-crypto-5.2.6.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/data/spring-data-mongodb/2.2.10.RELEASE/spring-data-mongodb-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/spring-tx/5.2.9.RELEASE/spring-tx-5.2.9.RELEASE.jar:/Users/allen.hou/.m2/repository/org/mongodb/mongo-java-driver/3.12.8/mongo-java-driver-3.12.8.jar:/Users/allen.hou/.m2/repository/org/springframework/data/spring-data-commons/2.2.10.RELEASE/spring-data-commons-2.2.10.RELEASE.jar:/Users/allen.hou/.m2/repository/com/veritas/appliance/rmapi/2.0.141/rmapi-2.0.141.jar:/Users/allen.hou/.m2/repository/com/veritas/appliance/auditinterceptor/1.0.2/auditinterceptor-1.0.2.jar:/Users/allen.hou/.m2/repository/org/springframework/hateoas/spring-hateoas/1.0.5.RELEASE/spring-hateoas-1.0.5.RELEASE.jar:/Users/allen.hou/.m2/repository/org/springframework/plugin/spring-plugin-core/2.0.0.RELEASE/spring-plugin-core-2.0.0.RELEASE.jar:/Users/allen.hou/.m2/repository/com/veritas/appliance/applianceutil/1.0.122/applianceutil-1.0.122.jar:/Users/allen.hou/.m2/repository/com/wordnik/swagger-core/1.5.1-M2/swagger-core-1.5.1-M2.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.11.4/jackson-annotations-2.11.4.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-joda/2.10.5/jackson-datatype-joda-2.10.5.jar:/Users/allen.hou/.m2/repository/joda-time/joda-time/2.10.6/joda-time-2.10.6.jar:/Users/allen.hou/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.10.5/jackson-dataformat-yaml-2.10.5.jar:/Users/allen.hou/.m2/repository/com/wordnik/swagger-models/1.5.1-M2/swagger-models-1.5.1-M2.jar:/Users/allen.hou/.m2/repository/com/wordnik/swagger-annotations/1.5.1-M2/swagger-annotations-1.5.1-M2.jar:/Users/allen.hou/.m2/repository/javax/validation/validation-api/2.0.1.Final/validation-api-2.0.1.Final.jar:/Users/allen.hou/.m2/repository/org/codehaus/janino/janino/3.1.2/janino-3.1.2.jar:/Users/allen.hou/.m2/repository/org/codehaus/janino/commons-compiler/3.1.2/commons-compiler-3.1.2.jar:/Applications/IntelliJ IDEA CE.app/Contents/plugins/testng/lib/jcommander-1.27.jar" org.testng.RemoteTestNGStarter -usedefaultlisteners false -socket54332 @w@/private/var/folders/1z/fs0s0cxj4ydc1r82qftmwx7c0000gn/T/idea_working_dirs_testng.tmp -temp /private/var/folders/1z/fs0s0cxj4ydc1r82qftmwx7c0000gn/T/idea_testng.tmp
java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:25)
	at mockit.internal.startup.Startup.initializeIfPossible(Startup.java:212)
	at mockit.integration.testng.Initializer.<init>(Initializer.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
java.util.ServiceConfigurationError: org.testng.ITestNGListener: Provider mockit.integration.testng.Initializer could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:965)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:914)
	at org.testng.TestNG.run(TestNG.java:1037)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)
Caused by: java.lang.IllegalStateException: JMockit requires a Java 6+ VM
	at mockit.internal.startup.AgentInitialization.loadAgentFromLocalJarFile(AgentInitialization.java:25)
	at mockit.internal.startup.Startup.initializeIfPossible(Startup.java:212)
	at mockit.integration.testng.Initializer.<init>(Initializer.java:29)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 7 more

Process finished with exit code 255

**Comment by milossesic** [comment]
As suggested by the dude, ramping up the version of jmockit solved it.

**Comment by realduke2000** [comment]
I downloaded the java8 from zulu, and update the runtime enviornment for this...
