### ISSUE TITLE
Build Failure MacOS Catalina 10.15.2

### ISSUE THREAD

**Issue by mstarkie** [jmockit/jmockit1#651]
Clone and build from main

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/Michael/Downloads/apache-maven-3.6.3
Java version: 1.8.0_131, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.2", arch: "x86_64", family: "mac"
MacBook-Air:surefire-reports Michael$ 

///////////

ERROR] Failures: 
[ERROR]   TestNGFakingTest.tearDownTestMethod:47 NoClassDefFound Could not initialize cl...
[ERROR]   TestNGFakingTest.testSomething:41 » ExceptionInInitializer
[INFO] 
[ERROR] Tests run: 38, Failures: 2, Errors: 0, Skipped: 3
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:05 min
[INFO] Finished at: 2020-01-17T07:31:48-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project jmockit: There are test failures.

**Comment by mstarkie** [comment]
Ok. Maybe it's related to the latest Mac OS.  Here is the dump file:

# Created at 2020-01-18T08:08:20.151
System.exit() or native command error interrupted process checker.
java.lang.IllegalStateException: error [STOPPED] to read process 97570
        at org.apache.maven.surefire.booter.PpidChecker.checkProcessInfo(PpidChecker.java:145)
        at org.apache.maven.surefire.booter.PpidChecker.isProcessAlive(PpidChecker.java:124)
        at org.apache.maven.surefire.booter.ForkedBooter$2.run(ForkedBooter.java:214)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)
