### ISSUE TITLE
mockit.internal.ClassFile$NotFoundException

### ISSUE THREAD

**Issue by evdzhan** [jmockit/jmockit1#71]
Hi there,

I am facing the following error when I try to mock an abstract class with JMockit 1.12. With JMockit  1.11 it works fine.

Enviroment :  
OS Win7 64 bit
JDK 1.7.0_51 32 bit
JMockit 1.12

mockit.internal.ClassFile$NotFoundException: Unable to find class file for my.package.$Subclass_BaseWindow

The mockUp instantiation looks like : 

new MockUp < BaseWindow > () { 
 // override stuff here  
};

Here is the entire stack trace 
mockit.internal.ClassFile$NotFoundException: Unable to find class file for my.package.$Subclass_BaseWindow
    at mockit.internal.ClassFile.verifyClassFileFound(ClassFile.java:35)
    at mockit.internal.ClassFile.readClassFromClasspath(ClassFile.java:101)
    at mockit.internal.ClassFile.readFromFile(ClassFile.java:144)
    at mockit.internal.ClassFile.createReaderFromLastRedefinitionIfAny(ClassFile.java:118)
    at mockit.internal.mockups.MockClassSetup.createClassReaderForRealClass(MockClassSetup.java:135)
    at mockit.internal.mockups.MockClassSetup.modifyRealClass(MockClassSetup.java:113)
    at mockit.internal.mockups.MockClassSetup.redefineMethodsInClassHierarchy(MockClassSetup.java:90)
    at mockit.internal.mockups.MockClassSetup.redefineMethods(MockClassSetup.java:78)
    at mockit.MockUp.redefineMethods(MockUp.java:253)
    at mockit.MockUp.redefineClassOrImplementInterface(MockUp.java:223)
    at mockit.MockUp.<init>(MockUp.java:134)

**Comment by evdjo** [comment]
I am still having this issue as well... 1.14 doesn't seem to have fixed this. Any chance this is investigated again ? I have tried really hard to isolate the case but I can't. There isn't example case that I can provide.

**Comment by samuelliang** [comment]
I had the same issue. I found this situation is under mockup not expectations style. When I manual run test case is always fine. But run under maven(mvn clean test), always happened this issue. So, I suggest whether maven impact jmockit. Have any advise?

**Comment by ignaciotcrespo** [comment]
same problem here running tests manually with gradle and jacoco coverage enabled. Added a filter in jacoco 
```                       
**/*$Impl_*,
**/*$Subclass_*,
``` 
but still fails
