### ISSUE TITLE
Jmock unexpected invocation error

### ISSUE THREAD

**Issue by smrititaneja18** [jmockit/jmockit1#713]
I am getting below error when i am trying to run Jmock unit test case:

unexpected invocation : connection.prepareStatement("SELECT * FROM table_name WHERE column1 = ? AND  column2= ?")

`at org.jmock.internal.InvocationDispatcher.dispatch(InvocationDispatcher.java:85)
at org.jmock.Mockery.dispatch(Mockery.java:250)
at org.jmock.Mockery.access$100(Mockery.java:46)
at org.jmock.Mockery$MockObject.invoke(Mockery.java:290)
at org.jmock.internal.InvocationDiverter.invoke(InvocationDiverter.java:27)
at org.jmock.internal.FakeObjectMethods.invoke(FakeObjectMethods.java:38)
at org.jmock.internal.SingleThreadedPolicy$1.invoke(SingleThreadedPolicy.java:21)
at org.jmock.lib.legacy.ClassImposteriser$4.invoke(ClassImposteriser.java:136)
at $java.sql.Connection$$EnhancerByCGLIB$$cc8142f5.prepareStatement(<generated>)

Using jmock-2.5.1.jar

Can anyone help me with this error please? I m stuck with this error, this is failing every time i am running existing test cases.

**Comment by smrititaneja18** [comment]
Can anyone help me with this error please? I m stuck with this error, this is failing every time i am running existing test cases.

**Comment by Saljack** [comment]
Hi this is `JMockit` repository. You use `jMock` its repository is https://github.com/jmock-developers/jmock-library . Please close this ticket here and create it there.
