### ISSUE TITLE
Recording thread-safety

### ISSUE THREAD

**Issue by fdz-nelson-branco** [jmockit/jmockit1#718]
# Issue

**Disclaimer**: I'm not sure if this is an issue since I can't tell if it was meant to be thread-safe on recordings.

When recording mock calls, a parallel thread using mocks will generate recorded invocations.
This affects the records with possible overriding of a call or creating a mandatory expectation that will cause the failure of the test.

There are some locks that help to prevent this situation but not entirely since there's a race condition on it namely at:

```java
private static boolean notToBeMocked(@Nullable Object mock, @Nonnull String classDesc) {
    return
        RECORD_OR_REPLAY_LOCK.isHeldByCurrentThread() ||
        TEST_ONLY_PHASE_LOCK.isLocked() && !TEST_ONLY_PHASE_LOCK.isHeldByCurrentThread() ||
        !TestRun.mockFixture().isStillMocked(mock, classDesc);
}
```

when the lock `RECORD_OR_REPLAY_LOCK` isn't yet adquired by the recording thread, and gets adquired after, yet during the other thread execution using mocks.

## Project to generate record-phase race condition

This project includes a test that uses a mock object on a separated thread while the main thread is creating `Expectations` (a.k.a. record phase).

## Versions

The issue was tested and found on both `1.35` and `1.49`.

## Reproduce

Using the version `1.49`, add a breakpoint at `mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:138)` with the condition `instance.getCurrentPhase() instanceof RecordPhase`.

Debug the project's `foo.JMockitParallelExecutionTest` test class.

### Thread dump

```
"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:152)
	  at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1265)
	  at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:462)
	  at mockit.internal.expectations.RecordAndReplayExecution.endInvocations(RecordAndReplayExecution.java:348)
	  at mockit.internal.expectations.ActiveInvocations.endInvocations(ActiveInvocations.java:154)
	  at foo.JMockitParallelExecutionTest$1.<init>(JMockitParallelExecutionTest.java:26)
	  at foo.JMockitParallelExecutionTest.test(JMockitParallelExecutionTest.java:24)
	  at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:498)
	  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)

"ForkJoinPool.commonPool-worker-1@1225" daemon prio=5 tid=0xd nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at mockit.internal.expectations.RecordAndReplayExecution.recordOrReplay(RecordAndReplayExecution.java:138)
	  at foo.$Impl_Dependency1.bar(Unknown Source:-1)
	  at foo.JMockitParallelExecutionTest.lambda$test$0(JMockitParallelExecutionTest.java:19)
	  at foo.JMockitParallelExecutionTest$$Lambda$1.1308927845.run(Unknown Source:-1)
	  at java.util.concurrent.CompletableFuture$AsyncRun.run$$$capture(CompletableFuture.java:1640)
[jmockit-paralell-racecondition.zip](https://github.com/jmockit/jmockit1/files/7792572/jmockit-paralell-racecondition.zip)

	  at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:-1)
	  at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	  at java.util.concurrent.ForkJoinTask.doExec$$$capture(ForkJoinTask.java:289)
	  at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:-1)
	  at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	  at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	  at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```
[jmockit-paralell-racecondition.zip](https://github.com/jmockit/jmockit1/files/7792576/jmockit-paralell-racecondition.zip)

**Comment by rliesenfeld** [comment]
JMockit is meant to be thread-safe for tests that execute multi-threaded code (as long as such tests don't leave background code running after the end of the test which started it). It does not support concurrent test execution in a single process.

So, during the recording or verification phases, only the main (test execution) thread should be accessing mocked classes or instances. During replay, multiple threads should be able to. The JMockit test suite itself has tests that do this.
