### ISSUE TITLE
Mocking constructor with THIS does not work

### ISSUE THREAD

**Issue by Horcrux7** [jmockit/jmockit1#721]
Please provide the following information:

* Version of JMockit that was used: 1.49

* Description of the problem or enhancement request:

The follow sample produce an NullPointerException in the original constructor instead printing the output of the mocked constructor. This has worked with version 1.46.

```
Exception in thread "main" java.lang.NullPointerException
	at TestMock$Sample.<init>(TestMock.java:17)
	at TestMock.main(TestMock.java:12)
```

``` java
import java.io.IOException;
import java.io.InputStream;
import java.net.URL;

import mockit.Mock;
import mockit.MockUp;

public class TestMock {

    public static void main( String[] args ) throws IOException {
        new MockSample();
        new Sample( (URL)null );
    }

    static class Sample {
        Sample( URL url ) throws IOException {
            this( url.openStream() );
            System.err.println( "Sample URL" );
        }

        public Sample( InputStream stream ) throws IOException {
            System.err.println( "Sample InputStream" );
        }
    }

    static class MockSample extends MockUp<Sample> {
        @Mock
        public void $init( URL url ) throws IOException {
            System.err.println( "$init " + url );
        }
    }
}
```

**Comment by rliesenfeld** [comment]
It's normal behavior. The "$init" mock only applies to the code *after* the "this(...)" call inside Sample's constructor.
